//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP02_Maykova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products
    {
        public int ID_partner_products { get; set; }
        public Nullable<int> ID_Products { get; set; }
        public Nullable<int> ID_Partners { get; set; }
        public Nullable<long> Num_of_products { get; set; }
        public Nullable<System.DateTime> Date_of_sale { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
